apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  nginx.conf: |-
    user nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        server {
            listen 80;
            location /success {
                default_type text/plain;
                return 200 "Success! \n";
            }
            location /error_500 {
                default_type text/plain;
                return 500 " HTTP error 500 \n";
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-app
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
      volumes:
      - name: config-app
        configMap:
          name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app
